<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="BLRNIDGWN05614" name="example.NewTest" tests="11" failures="0" timestamp="12 Sep 2019 10:32:16 GMT" time="18.884" errors="1">
  <testcase name="testEasySeven" time="0.681" classname="example.NewTest"/>
  <testcase name="testEasyNine" time="0.914" classname="example.NewTest"/>
  <testcase name="testEasyOne" time="0.787" classname="example.NewTest"/>
  <testcase name="testEasyThree" time="0.796" classname="example.NewTest"/>
  <testcase name="testEasyTen" time="0.792" classname="example.NewTest"/>
  <testcase name="testEasyEight" time="11.647" classname="example.NewTest"/>
  <testcase name="testEasyEleven" time="0.641" classname="example.NewTest">
    <error type="java.lang.AssertionError" message="">
      <![CDATA[java.lang.AssertionError: 
	at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
	at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:24)
	at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:33)
	at example.NewTest.testEasyEleven(NewTest.java:136)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </error>
  </testcase> <!-- testEasyEleven -->
  <testcase name="testEasyTwo" time="0.460" classname="example.NewTest"/>
  <testcase name="testEasySix" time="0.798" classname="example.NewTest"/>
  <testcase name="testEasyfive" time="0.683" classname="example.NewTest"/>
  <testcase name="testEasyfour" time="0.685" classname="example.NewTest"/>
</testsuite> <!-- example.NewTest -->
